import { style } from '@material-ui/system';
import {useState,useEffect} from 'react'
import Layout from '../../components/layout/Layout'
import styles from '../../styles/Country.module.css'
import Head from 'next/head'


export const getCountry=async(code)=>{
    const response=await fetch(`https://restcountries.eu/rest/v2/alpha/${code}`);
    const country=await response.json();
    

    return country;
}


const Country=({country})=>{
    const [borders,setBorders]=useState([]);
    const getBorders=async()=>{
        const borders= await Promise.all( country.borders.map((b)=>getCountry(b)));
        setBorders(borders);
    }
    
    useEffect(()=>{
    getBorders();
    },[])
    return(
        <>
        <Head>
          <title>{country.name}</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
     <Layout>
        <div className={styles.container}>
            <div className={styles.primary}>
            <div className={styles.flag}>
        
        <img src={country.flag} alt={country.name}/>
        <h1>{country.name}</h1>
        <p>{country.region}</p>
        <div className={styles.flex}>
            <div className={styles.box}>
            <h2>{country.population}</h2>
            <p>population</p>
            </div>
            <div className={styles.box}>
            <h2>{country.area}</h2>
            <p>Area</p>
            </div>
        </div>
    </div>
            </div>
           
              <div className={styles.details_container}>
                  <div className={styles.details}>
                      <h4>Details</h4>
                      <div className={styles.detail_box}>
                      <p className={styles.title}>Capital</p>
                      <h4>{country.capital}</h4>     
                      </div>
                       
                      <div className={styles.detail_box}>
                      <p className={styles.title}>Language</p>
                      <h4>{country.languages.map((l)=>(<span key={l.name} className={styles.language} >{l.name} </span>))}</h4>     
                      </div>
                      
                      <div className={styles.detail_box}>
                      <p className={styles.title}>Currencies</p>
                      <h4>{country.currencies.map((l)=>(<span key={l.name} className={styles.currencies} >{l.name} </span>))}</h4>     
                      </div>
                       
                      
                      <div className={styles.detail_box}>
                      <p className={styles.title}>Native Name</p>
                      <h4>{country.nativeName}</h4>     
                      </div>
                     
                      <div className={styles.detail_box}>
                      <p className={styles.title}>Gini</p>
                      <h4>{country.gini}%</h4>     
                      </div>
                      
                     
                  </div>
                  <h2 className={styles.neighbour}>Neighbouring Countries</h2>
                  <div className={styles.borders}>
                      
                 
                   {
                       borders.map((item)=>(
                           <div className={styles.country} key={item.name}>  
                               <img src={item.flag} alt={item.name}/>
                               <p>{item.name}</p>
                            </div>   
                       ))
                   }
     </div>
              </div>
        </div>

     </Layout>
     </>
    )
}
export default Country;

export const getServerSideProps=async(context)=>{
        const {params}=context;
 
const country=await getCountry(params.id);
     
return{
    props:{
        country
    }
}

}